In [46]:
import pandas as pd
import requests
import matplotlib.pyplot as plt

print(requests.__version__)

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

2.34.2

In [3]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [4]:
#url de la API
api_url='https://api.yelp.com/v3/businesses/search'

#estos datos corresponden a una cuenta de usuario creada previamente
clientid='GWOCZh9-BmZxtdsAjr7Gug'
apikey='FHVvXoNmTXIl9DuxYis7AV5uLPujm9MLwrhgs5NgvCfaOxd3V6mxt6dQU8eEqYJiGxe816XATx7ufWjbMWqbV-2Uku1jxBJv8BGRC74NroLPl27PDQqs0tDixit-YHYx'
headers={'Authorization':'Bearer %s'%apikey}

In [ ]:
ciudad = "Miami"

In [ ]:
# De esta manera se consulta el API de Yelp para obtener información sobre restaurantes en la ciudad especificada
response=requests.get(api_url,params=params,headers=headers)
data=response.json()
rams={'term':'restaurants','location': ciudad,'limit':50}
data

In [48]:
data.keys()

dict_keys(['businesses', 'total', 'region'])

In [49]:
print('En total la base de datos registra %d restaurants'%data['total'])

En total la base de datos registra 5900 restaurants

In [50]:
data['businesses']

[{'id': 'XmZO_0VytcQbXiuVLA9lmg',
  'alias': 'calamillor-miami',
  'name': 'CalaMillor',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/j54ss1GKNrqr_RLkP28q5A/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/calamillor-miami?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 226,
  'categories': [{'alias': 'spanish', 'title': 'Spanish'},
   {'alias': 'desserts', 'title': 'Desserts'}],
  'rating': 4.1,
  'coordinates': {'latitude': 25.733847292941373,
   'longitude': -80.2866818010807},
  'transactions': ['delivery', 'pickup'],
  'location': {'address1': '4000 SW 57th Ave',
   'address2': '',
   'address3': '',
   'city': 'Miami',
   'zip_code': '33155',
   'country': 'US',
   'state': 'FL',
   'display_address': ['4000 SW 57th Ave', 'Miami, FL 33155']},
  'phone': '+13054563938',
  'display_phone': '(305) 456-3938',
  'distance': 2115.1014745862904},
 {'id': '4mmMeIIVKFwH6Zdm9Awbpw',
  'alias': 'belly-fish-miami-3',
  'name': 'Belly Fish',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/vJs1IyJJ-uy1fwz6SVV7IA/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/belly-fish-miami-3?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 127,
  'categories': [{'alias': 'sushi', 'title': 'Sushi Bars'},
   {'alias': 'japanese', 'title': 'Japanese'},
   {'alias': 'seafood', 'title': 'Seafood'},
   {'alias': 'sushi', 'title': 'Sushi Bars'},
   {'alias': 'japanese', 'title': 'Japanese'},
   {'alias': 'seafood', 'title': 'Seafood'},
   {'alias': 'sushi', 'title': 'Sushi Bars'},
   {'alias': 'japanese', 'title': 'Japanese'},
   {'alias': 'seafood', 'title': 'Seafood'}],
  'rating': 4.3,
  'coordinates': {'latitude': 25.73394497090103,
   'longitude': -80.25557414688785},
  'transactions': [],
  'price': '$$',
  'location': {'address1': '3060 SW 37th Ave',
   'address2': 'Ste 104',
   'address3': '',
   'city': 'Miami',
   'zip_code': '33133',
   'country': 'US',
   'state': 'FL',
   'display_address': ['3060 SW 37th Ave', 'Ste 104', 'Miami, FL 33133']},
  'phone': '+17865506267',
  'display_phone': '(786) 550-6267',
  'distance': 3871.682070456338},
 {'id': 'FlwH8ubnK7rBYJaqAyr6fA',
  'alias': 'ventanas-restaurant-bar-and-lounge-miami',
  'name': 'Ventanas Restaurant Bar & Lounge',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/1g2acJK9Iwj1Z2M0YtO6Ow/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/ventanas-restaurant-bar-and-lounge-miami?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 12,
  'categories': [{'alias': 'latin', 'title': 'Latin American'},
   {'alias': 'bars', 'title': 'Bars'}],
  'rating': 4.2,
  'coordinates': {'latitude': 25.735223, 'longitude': -80.257644},
  'transactions': ['delivery'],
  'price': '$$',
  'location': {'address1': '3861 SW 40th St',
   'address2': '',
   'address3': '',
   'city': 'Miami',
   'zip_code': '33146',
   'country': 'US',
   'state': 'FL',
   'display_address': ['3861 SW 40th St', 'Miami, FL 33146']},
  'phone': '+17863539460',
  'display_phone': '(786) 353-9460',
  'distance': 3632.356512476082},
 {'id': 'sWSzsElqCo-HHO_LUJWhow',
  'alias': 'serafina-miami',
  'name': 'Serafina',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/a97gJX-5G7EgL3_XrAEMJg/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/serafina-miami?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 46,
  'categories': [{'alias': 'bars', 'title': 'Bars'},
   {'alias': 'italian', 'title': 'Italian'}],
  'rating': 4.1,
  'coordinates': {'latitude': 25.781001476817252,
   'longitude': -80.19134333656665},
  'transactions': [],
  'location': {'address1': '652 NE 2nd Ave',
   'address2': '',
   'address3': '',
   'city': 'Miami',
   'zip_code': '33132',
   'country': 'US',
   'state': 'FL',
   'display_address': ['652 NE 2nd Ave', 'Miami, FL 33132']},
  'phone': '+13059021851',
  'display_phone': '(305) 902-1851',
  'distance': 10178.23264715558},
 {'id': '6WjQnu6QluI0WdHBdI_0zw',
  'alias': 'bro-s-hot-chicken-miami',
  'name': 'Bro’s Hot Chicken',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/jHW6vQpRVk27Ps5Lf7iC-w/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/bro-s-hot-chicken-miami?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 112,
  'categories': [{'alias': 'chickenshop', 'title': 'Chicken Shop'}],
  'rating': 4.2,
  'coordinates': {'latitude': 25.76238774117262,
   'longitude': -80.30557441040257},
  'transactions': ['delivery', 'pickup'],
  'price': '$$',
  'location': {'address1': '936 SW 67th Ave',
   'address2': '',
   'address3': '',
   'city': 'Miami',
   'zip_code': '33144',
   'country': 'US',
   'state': 'FL',
   'display_address': ['936 SW 67th Ave', 'Miami, FL 33144']},
  'phone': '+17863073159',
  'display_phone': '(786) 307-3159',
  'distance': 2051.7130531448815},
 {'id': 'K6zJCTpwqQ4jL5IwqJPHaw',
  'alias': 'aromas-del-peru-west-miami-4',
  'name': 'Aromas del Peru',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/_7GZCQzv_nNIFrCVr-WCOQ/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/aromas-del-peru-west-miami-4?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 414,
  'categories': [{'alias': 'peruvian', 'title': 'Peruvian'},
   {'alias': 'seafood', 'title': 'Seafood'}],
  'rating': 4.0,
  'coordinates': {'latitude': 25.7639979, 'longitude': -80.2890612},
  'transactions': ['delivery', 'pickup'],
  'price': '$$',
  'location': {'address1': '5757 SW 8th St',
   'address2': '',
   'address3': '',
   'city': 'West Miami',
   'zip_code': '33144',
   'country': 'US',
   'state': 'FL',
   'display_address': ['5757 SW 8th St', 'West Miami, FL 33144']},
  'phone': '+17863470506',
  'display_phone': '(786) 347-0506',
  'distance': 1246.0538306922235},
 {'id': 'zVCp5OmpE5Y_itQTALgBtg',
  'alias': 'drinking-pig-bbq-miami-2',
  'name': 'Drinking Pig BBQ',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/266YpLrTDDe5D_p1G8539Q/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/drinking-pig-bbq-miami-2?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 85,
  'categories': [{'alias': 'bbq', 'title': 'Barbeque'}],
  'rating': 4.4,
  'coordinates': {'latitude': 25.727325, 'longitude': -80.24344},
  'transactions': [],
  'location': {'address1': '3444 Main Hwy',
   'address2': 'Ste 16',
   'address3': '',
   'city': 'Miami',
   'zip_code': '33133',
   'country': 'US',
   'state': 'FL',
   'display_address': ['3444 Main Hwy', 'Ste 16', 'Miami, FL 33133']},
  'phone': '+17865344244',
  'display_phone': '(786) 534-4244',
  'distance': 5337.596849845736},
 {'id': 'eo2W_Hakq3SVGUsUSBHvGw',
  'alias': '1-800-lucky-miami-2',
  'name': '1-800-Lucky',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/-9HmE7mElkNa7K0M9VhoyQ/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/1-800-lucky-miami-2?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 1694,
  'categories': [{'alias': 'asianfusion', 'title': 'Asian Fusion'},
   {'alias': 'bars', 'title': 'Bars'},
   {'alias': 'karaoke', 'title': 'Karaoke'}],
  'rating': 4.1,
  'coordinates': {'latitude': 25.79931, 'longitude': -80.198},
  'transactions': ['delivery'],
  'price': '$$',
  'location': {'address1': '143 NW 23rd St',
   'address2': '',
   'address3': '',
   'city': 'Miami',
   'zip_code': '33127',
   'country': 'US',
   'state': 'FL',
   'display_address': ['143 NW 23rd St', 'Miami, FL 33127']},
  'phone': '+13057689826',
  'display_phone': '(305) 768-9826',
  'distance': 10401.384990501072},
 {'id': '6vL6vsYoQ9h1SqDHbgEvrg',
  'alias': 'the-korean-chef-kendall',
  'name': 'The Korean Chef',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/vX9h2QvEwl7ryvW4gGzSyA/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/the-korean-chef-kendall?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 67,
  'categories': [{'alias': 'korean', 'title': 'Korean'}],
  'rating': 4.3,
  'coordinates': {'latitude': 25.68752, 'longitude': -80.363156},
  'transactions': [],
  'location': {'address1': '10471 SW 88th St',
   'address2': 'Ste B103',
   'address3': '',
   'city': 'Kendall',
   'zip_code': '33176',
   'country': 'US',
   'state': 'FL',
   'display_address': ['10471 SW 88th St', 'Ste B103', 'Kendall, FL 33176']},
  'phone': '+13058498867',
  'display_phone': '(305) 849-8867',
  'distance': 10470.78963579743},
 {'id': 'E9o0PMAyrBar8NhBYJzyXA',
  'alias': 'bouchon-bistro-coral-gables',
  'name': 'Bouchon Bistro',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/Oh4zmm_N7sn60aXOjIG_Pg/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/bouchon-bistro-coral-gables?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 178,
  'categories': [{'alias': 'french', 'title': 'French'},
   {'alias': 'wine_bars', 'title': 'Wine Bars'},
   {'alias': 'cocktailbars', 'title': 'Cocktail Bars'}],
  'rating': 4.0,
  'coordinates': {'latitude': 25.75298833063511,
   'longitude': -80.2567275423279},
  'transactions': [],
  'location': {'address1': '2101 Galiano St',
   'address2': '',
   'address3': '',
   'city': 'Coral Gables',
   'zip_code': '33134',
   'country': 'US',
   'state': 'FL',
   'display_address': ['2101 Galiano St', 'Coral Gables, FL 33134']},
  'phone': '+13059901360',
  'display_phone': '(305) 990-1360',
  'distance': 3137.0904075918197},
 {'id': 'H6KWK8GNk9bxUsjOOgHW1Q',
  'alias': 'duffys-tavern-miami',
  'name': "Duffy's Tavern",
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/3wVBJ958NiGCq2FancTqVg/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/duffys-tavern-miami?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 257,
  'categories': [{'alias': 'bars', 'title': 'Bars'},
   {'alias': 'burgers', 'title': 'Burgers'}],
  'rating': 3.8,
  'coordinates': {'latitude': 25.7511641166699,
   'longitude': -80.2875455514379},
  'transactions': ['pickup'],
  'price': '$$',
  'location': {'address1': '2108 SW 57th Ave',
   'address2': '',
   'address3': '',
   'city': 'Miami',
   'zip_code': '33155',
   'country': 'US',
   'state': 'FL',
   'display_address': ['2108 SW 57th Ave', 'Miami, FL 33155']},
  'phone': '+13052646580',
  'display_phone': '(305) 264-6580',
  'distance': 191.90300147145925},
 {'id': 'fEWNFu1iehstzjmYC_EHCA',
  'alias': 'doobi-doobap-miami-2',
  'name': 'Doobi Doobap',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/eGbS_m4TqIPi25AYK7eeCg/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/doobi-doobap-miami-2?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 21,
  'categories': [{'alias': 'fooddeliveryservices',
    'title': 'Food Delivery Services'},
   {'alias': 'korean', 'title': 'Korean'}],
  'rating': 4.6,
  'coordinates': {'latitude': 25.782964953294005, 'longitude': -80.1944893},
  'transactions': ['delivery', 'pickup'],
  'location': {'address1': '31 NW 9th St',
   'address2': '',
   'address3': '',
   'city': 'Miami',
   'zip_code': '33136',
   'country': 'US',
   'state': 'FL',
   'display_address': ['31 NW 9th St', 'Miami, FL 33136']},
  'phone': '+17542548613',
  'display_phone': '(754) 254-8613',
  'distance': 9950.282376090821},
 {'id': 'kJfImCoyZI_pfedQ0rad9A',
  'alias': 'ami-ami-coral-gables',
  'name': 'Ami Ami',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/4J0S26InNGVn_OtRU-WS-g/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/ami-ami-coral-gables?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 3,
  'categories': [{'alias': 'cafes', 'title': 'Cafes'},
   {'alias': 'mediterranean', 'title': 'Mediterranean'},
   {'alias': 'breakfast_brunch', 'title': 'Breakfast & Brunch'}],
  'rating': 4.3,
  'coordinates': {'latitude': 25.749113, 'longitude': -80.261141},
  'transactions': ['restaurant_reservation'],
  'location': {'address1': '318 Miracle Mile',
   'address2': '',
   'address3': '',
   'city': 'Coral Gables',
   'zip_code': '33134',
   'country': 'US',
   'state': 'FL',
   'display_address': ['318 Miracle Mile', 'Coral Gables, FL 33134']},
  'phone': '+17863978340',
  'display_phone': '(786) 397-8340',
  'distance': 2726.060790523038},
 {'id': 'Y56r8q8P7Ed5JFbL_TPtAg',
  'alias': 'disco-donkey-miami',
  'name': 'Disco Donkey',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/LNxIelDRm5u2OcfsJN9OgQ/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/disco-donkey-miami?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 19,
  'categories': [{'alias': 'burgers', 'title': 'Burgers'}],
  'rating': 3.7,
  'coordinates': {'latitude': 25.773568681511154,
   'longitude': -80.18998221727458},
  'transactions': [],
  'location': {'address1': '209 SE 1st St',
   'address2': '',
   'address3': '',
   'city': 'Miami',
   'zip_code': '33131',
   'country': 'US',
   'state': 'FL',
   'display_address': ['209 SE 1st St', 'Miami, FL 33131']},
  'phone': '+13058902655',
  'display_phone': '(305) 890-2655',
  'distance': 10087.905781830554},
 {'id': '-fCMdb5Rfc0oTOWBnW9RSA',
  'alias': 'la-rosa-fine-cuban-cuisine-miami',
  'name': 'La Rosa Fine Cuban Cuisine',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/P-uLajC4zr-A44lQys5Jtg/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/la-rosa-fine-cuban-cuisine-miami?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 542,
  'categories': [{'alias': 'cuban', 'title': 'Cuban'},
   {'alias': 'bars', 'title': 'Bars'},
   {'alias': 'steak', 'title': 'Steakhouses'}],
  'rating': 4.1,
  'coordinates': {'latitude': 25.779044, 'longitude': -80.262671},
  'transactions': ['pickup'],
  'price': '$$',
  'location': {'address1': '4041 NW 7th St',
   'address2': '',
   'address3': '',
   'city': 'Miami',
   'zip_code': '33126',
   'country': 'US',
   'state': 'FL',
   'display_address': ['4041 NW 7th St', 'Miami, FL 33126']},
  'phone': '+13055411715',
  'display_phone': '(305) 541-1715',
  'distance': 3867.360398847775},
 {'id': 'wsJQm_iSAj2jLeK9jaCQdg',
  'alias': 'hi-pot-miami-miami',
  'name': 'Hi Pot Miami',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/Rrk0EbqZdrucVwzKB9X-ow/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/hi-pot-miami-miami?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 287,
  'categories': [{'alias': 'taiwanese', 'title': 'Taiwanese'},
   {'alias': 'hotpot', 'title': 'Hot Pot'},
   {'alias': 'ramen', 'title': 'Ramen'}],
  'rating': 4.4,
  'coordinates': {'latitude': 25.752836, 'longitude': -80.367636},
  'transactions': ['delivery', 'pickup'],
  'price': '$$',
  'location': {'address1': '1665 SW 107th Ave',
   'address2': '',
   'address3': '',
   'city': 'Miami',
   'zip_code': '33165',
   'country': 'US',
   'state': 'FL',
   'display_address': ['1665 SW 107th Ave', 'Miami, FL 33165']},
  'phone': '+17868038618',
  'display_phone': '(786) 803-8618',
  'distance': 7970.503448316423},
 {'id': 'qR35bCaZAKozz0_ntddWgg',
  'alias': 'el-carajo-international-tapas-and-wines-miami-3',
  'name': 'El Carajo International Tapas & Wines',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/FQtfHwIliKfW8o_FjFlhZg/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/el-carajo-international-tapas-and-wines-miami-3?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 815,
  'categories': [{'alias': 'spanish', 'title': 'Spanish'},
   {'alias': 'tapas', 'title': 'Tapas Bars'},
   {'alias': 'wine_bars', 'title': 'Wine Bars'}],
  'rating': 4.1,
  'coordinates': {'latitude': 25.7466309778868,
   'longitude': -80.2215504282417},
  'transactions': ['delivery', 'restaurant_reservation'],
  'price': '$$',
  'location': {'address1': '2465 SW 17th Ave',
   'address2': '',
   'address3': '',
   'city': 'Miami',
   'zip_code': '33145',
   'country': 'US',
   'state': 'FL',
   'display_address': ['2465 SW 17th Ave', 'Miami, FL 33145']},
  'phone': '+13058562424',
  'display_phone': '(305) 856-2424',
  'distance': 6695.785886855327},
 {'id': 'bphcfZUfxkGUV4l87BCIDg',
  'alias': 'cove-restaurant-miami',
  'name': 'Cove Restaurant',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/JD9E5SNq6g0BB7HaJ31vkA/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/cove-restaurant-miami?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 17,
  'categories': [{'alias': 'hotels', 'title': 'Hotels'},
   {'alias': 'restaurants', 'title': 'Restaurants'}],
  'rating': 3.2,
  'coordinates': {'latitude': 25.781903248474006, 'longitude': -80.2784943},
  'transactions': [],
  'location': {'address1': '5101 Blue Lagoon Dr',
   'address2': '',
   'address3': '',
   'city': 'Miami',
   'zip_code': '33126',
   'country': 'US',
   'state': 'FL',
   'display_address': ['5101 Blue Lagoon Dr', 'Miami, FL 33126']},
  'phone': '+13052621000',
  'display_phone': '(305) 262-1000',
  'distance': 3371.5824519462067},
 {'id': 'byXml8ucI-z68JnV7aFpTg',
  'alias': 'china-express-miami-2',
  'name': 'China Express',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/w3v0ReqwshHycPmBIreUUw/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/china-express-miami-2?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 193,
  'categories': [{'alias': 'chinese', 'title': 'Chinese'}],
  'rating': 4.1,
  'coordinates': {'latitude': 25.77057, 'longitude': -80.28882},
  'transactions': ['delivery', 'pickup'],
  'price': '$',
  'location': {'address1': '5748 W Flagler St',
   'address2': '',
   'address3': '',
   'city': 'Miami',
   'zip_code': '33144',
   'country': 'US',
   'state': 'FL',
   'display_address': ['5748 W Flagler St', 'Miami, FL 33144']},
  'phone': '+13056398281',
  'display_phone': '(305) 639-8281',
  'distance': 1969.6559715958845},
 {'id': 'Bs2wZRwOxbiMfS_HYHLc3w',
  'alias': 'ossobuco-miami-2',
  'name': 'Ossobuco Miami- Steak house',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/esPXkizvD2Q6EI2aze7F4w/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/ossobuco-miami-2?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 163,
  'categories': [{'alias': 'steak', 'title': 'Steakhouses'},
   {'alias': 'modern_european', 'title': 'Modern European'},

In [11]:
df_yelp_v1 = pd.DataFrame(data['businesses'])

In [33]:
display(df_yelp_v1.head(3))

,id,alias,name,image_url,is_closed,url,review_count,categories,rating,coordinates,transactions,price,location,phone,display_phone,distance
0,UXHxLN3DcDGI57uDIfCuJA,olds-havana-cuban-bar-and-cocina-miami,Old's Havana Cuban Bar & Cocina,https://s3-media0.fl.yelpcdn.com/bphoto/OyMD-x...,False,https://www.yelp.com/biz/olds-havana-cuban-bar...,3289,"[{'alias': 'cuban', 'title': 'Cuban'}, {'alias...",4.4,"{'latitude': 25.765607074496565, 'longitude': ...",[pickup],$$,"{'address1': '1442 SW 8th St', 'address2': '',...",+17865182196,(786) 518-2196,7038.216305
1,oxtMfBGmVNE18pFVuw7lFg,fratellino-coral-gables-2,Fratellino,https://s3-media0.fl.yelpcdn.com/bphoto/yGP5fN...,False,https://www.yelp.com/biz/fratellino-coral-gabl...,1940,"[{'alias': 'italian', 'title': 'Italian'}]",4.8,"{'latitude': 25.74917, 'longitude': -80.26011}","[delivery, pickup, restaurant_reservation]",$$$,"{'address1': '264 Miracle Mile', 'address2': '...",+17864520068,(786) 452-0068,2834.064937
2,O4gh_gZPp1zW9QtC1aMHWw,house-of-food-porn-miami-3,House of Food Porn,https://s3-media0.fl.yelpcdn.com/bphoto/YZJP20...,False,https://www.yelp.com/biz/house-of-food-porn-mi...,182,"[{'alias': 'sushi', 'title': 'Sushi Bars'}, {'...",4.8,"{'latitude': 25.8326319884545, 'longitude': -8...",[],NaN,"{'address1': '197 NW 62nd St', 'address2': '',...",+13057880137,(305) 788-0137,12507.730930

In [44]:
display(df_yelp_v2.head(3))

,alias,title,id,name,review_count,rating,price
0,spanish,Spanish,XmZO_0VytcQbXiuVLA9lmg,CalaMillor,226,4.1,NaN
1,desserts,Desserts,XmZO_0VytcQbXiuVLA9lmg,CalaMillor,226,4.1,NaN
2,sushi,Sushi Bars,4mmMeIIVKFwH6Zdm9Awbpw,Belly Fish,127,4.3,$$

In [39]:
contador = 0
lista_consolidar = []

while contador < 200:
    print('Contador: ',contador)
    params = {'term':'restaurants', 'location':ciudad, 'limit':50, 'offset':contador}
    response = requests.get(api_url, params=params, headers=headers)
    data = response.json()

    df_yelp_v2 = pd.json_normalize(
        data['businesses'],
        record_path=['categories'],
        meta=['id','name','review_count','rating','price'],
        errors='ignore'
    )
    lista_consolidar.append(df_yelp_v2)
    contador += 50

Contador:  0
Contador:  50
Contador:  100
Contador:  150

In [42]:
df_yelp_vf = pd.concat(lista_consolidar, ignore_index=True)

In [38]:
display(df_yelp_v2)

,alias,title,id,name,review_count,rating,price
0,asianfusion,Asian Fusion,WzLwihTClk64gXReMGlJQg,107 Taste,94,4.9,NaN
1,desserts,Desserts,WzLwihTClk64gXReMGlJQg,107 Taste,94,4.9,NaN
2,noodles,Noodles,WzLwihTClk64gXReMGlJQg,107 Taste,94,4.9,NaN
3,latin,Latin American,d881dT_RC64MOjXgH3fVuA,Latin Cafe 2000,656,3.6,$$
4,cuban,Cuban,d881dT_RC64MOjXgH3fVuA,Latin Cafe 2000,656,3.6,$$
5,cafes,Cafes,kJfImCoyZI_pfedQ0rad9A,Ami Ami,3,4.3,NaN
6,mediterranean,Mediterranean,kJfImCoyZI_pfedQ0rad9A,Ami Ami,3,4.3,NaN
7,breakfast_brunch,Breakfast & Brunch,kJfImCoyZI_pfedQ0rad9A,Ami Ami,3,4.3,NaN
8,peruvian,Peruvian,Tivvg8OnC753YS6n9sM2tQ,Taipa Peruvian Restaurant- Coral Gables,71,4.7,NaN
9,cuban,Cuban,SsIMtruy7PQXZZQx3Fs0vA,Cafe Versailles,420,3.9,$
10,cafes,Cafes,SsIMtruy7PQXZZQx3Fs0vA,Cafe Versailles,420,3.9,$
11,greek,Greek,RDV1XK_L4DDim9gNeg4etA,Calista Greek Seafood Taverna,234,4.4,$$$
12,seafood,Seafood,RDV1XK_L4DDim9gNeg4etA,Calista Greek Seafood Taverna,234,4.4,$$$
13,soulfood,Soul Food,bUAxNjDUfuXliayLcrZM2A,World Famous House of Mac,1505,4.2,$$
14,chicken_wings,Chicken Wings,bUAxNjDUfuXliayLcrZM2A,World Famous House of Mac,1505,4.2,$$
15,pizza,Pizza,bUAxNjDUfuXliayLcrZM2A,World Famous House of Mac,1505,4.2,$$
16,seafood,Seafood,d4pfwfJktfuTAQM51oj_ZQ,Monty's Raw Bar,1353,3.3,$$
17,tikibars,Tiki Bars,d4pfwfJktfuTAQM51oj_ZQ,Monty's Raw Bar,1353,3.3,$$
18,venues,Venues & Event Spaces,d4pfwfJktfuTAQM51oj_ZQ,Monty's Raw Bar,1353,3.3,$$
19,spanish,Spanish,z6V5OSxv20YQAv0sxhTriQ,El Rincon Asturiano,201,4.2,$$
20,latin,Latin American,FlwH8ubnK7rBYJaqAyr6fA,Ventanas Restaurant Bar & Lounge,12,4.2,$$
21,bars,Bars,FlwH8ubnK7rBYJaqAyr6fA,Ventanas Restaurant Bar & Lounge,12,4.2,$$
22,seafood,Seafood,hWrr6NgHsPN-ah0DSBsVQw,Islas Del Caribe Restaurant,28,4.2,$
23,honduran,Honduran,hWrr6NgHsPN-ah0DSBsVQw,Islas Del Caribe Restaurant,28,4.2,$
24,breakfast_brunch,Breakfast & Brunch,hWrr6NgHsPN-ah0DSBsVQw,Islas Del Caribe Restaurant,28,4.2,$
25,mediterranean,Mediterranean,2SJpb38UqPLwfMukVG8NKg,The Mediterranean Kitchen,8,4.3,NaN
26,french,French,Z4_MkMLc_CA4kkAYOj5EzA,Pastis Miami,410,4.4,NaN
27,tacos,Tacos,glR7sMvBkT8_Hcq5Mrl0KA,Mi Rinconcito Mexicano,1051,4.2,$$
28,steak,Steakhouses,zhP9n39XpszLR9DP7uBd1w,Rodeo Grill,12,4.2,NaN
29,argentine,Argentine,zhP9n39XpszLR9DP7uBd1w,Rodeo Grill,12,4.2,NaN
30,cocktailbars,Cocktail Bars,zhP9n39XpszLR9DP7uBd1w,Rodeo Grill,12,4.2,NaN
31,bbq,Barbeque,zVCp5OmpE5Y_itQTALgBtg,Drinking Pig BBQ,85,4.4,NaN
32,chickenshop,Chicken Shop,6WjQnu6QluI0WdHBdI_0zw,Bro’s Hot Chicken,112,4.2,$$
33,italian,Italian,FAT8rnPA1LNG0BW791LDzQ,La Sponda Ristorante & Grille,3,4.7,NaN
34,indpak,Indian,krKmADOKM1KjVm4F0rL8lQ,Ghee Indian Kitchen,928,4.3,$$$
35,bars,Bars,kSBE7iHfiYKdyNBIoB3Bvw,The Doral Yard,464,4.5,$$
36,musicvenues,Music Venues,kSBE7iHfiYKdyNBIoB3Bvw,The Doral Yard,464,4.5,$$
37,tradamerican,American,kSBE7iHfiYKdyNBIoB3Bvw,The Doral Yard,464,4.5,$$
38,peruvian,Peruvian,owu3ufM0B_sFgh-aVsLO4g,Manta Wynwood,319,4.4,$$$
39,cuban,Cuban,-fCMdb5Rfc0oTOWBnW9RSA,La Rosa Fine Cuban Cuisine,542,4.1,$$
40,bars,Bars,-fCMdb5Rfc0oTOWBnW9RSA,La Rosa Fine Cuban Cuisine,542,4.1,$$
41,steak,Steakhouses,-fCMdb5Rfc0oTOWBnW9RSA,La Rosa Fine Cuban Cuisine,542,4.1,$$
42,bars,Bars,sWSzsElqCo-HHO_LUJWhow,Serafina,46,4.1,NaN
43,italian,Italian,sWSzsElqCo-HHO_LUJWhow,Serafina,46,4.1,NaN
44,bars,Bars,H6KWK8GNk9bxUsjOOgHW1Q,Duffy's Tavern,257,3.8,$$
45,burgers,Burgers,H6KWK8GNk9bxUsjOOgHW1Q,Duffy's Tavern,257,3.8,$$
46,tradamerican,American,Gv5X1-qLTGZbwoz829-Xxg,Corona Beach House,927,4.1,$$
47,sportsbars,Sports Bars,Gv5X1-qLTGZbwoz829-Xxg,Corona Beach House,927,4.1,$$
48,salad,Salad,Gv5X1-qLTGZbwoz829-Xxg,Corona Beach House,927,4.1,$$
49,peruvian,Peruvian,K6zJCTpwqQ4jL5IwqJPHaw,Aromas del Peru,414,4.0,$$
50,seafood,Seafood,K6zJCTpwqQ4jL5IwqJPHaw,Aromas del Peru,414,4.0,$$
51,latin,Latin American,x9AjrNAXK2H8MNeklHp9Qw,Paseo Catracho,79,4.2,$
52,hotels,Hotels,bphcfZUfxkGUV4l87BCIDg,Cove Restaurant,17,3.2,NaN
53,restaurants,Restaurants,bphcfZUfxkGUV4l87BCIDg,Cove Restaurant,17,3.2,NaN
54,fooddeliveryservices,Food Delivery Services,fEWNFu1iehstzjmYC_EHCA,Doobi Doobap,21,4.6,NaN
55,korean,Korean,fEWNFu1iehstzjmYC_EHCA,Doobi Doobap,21,4.6,NaN
56,mediterranean,Mediterranean,6fv_GBeY64sepsNsNh3VGg,Fugato,132,4.7,$$$
57,italian,Italian,6fv_GBeY64sepsNsNh3VGg,Fugato,132,4.7,$$$
58,desserts,Desserts,6fv_GBeY64sepsNsNh3VGg,Fugato,132,4.7,$$$
59,burgers,Burgers,Y56r8q8P7Ed5JFbL_TPtAg,Disco Donkey,19,3.7,NaN
60,brazilian,Brazilian,VFIVZUyvMh59uxppfYV0IA,El Toro Loco Steakhouse Westchester,272,3.9,$$
61,steak,Steakhouses,VFIVZUyvMh59uxppfYV0IA,El Toro Loco Steakhouse Westchester,272,3.9,$$
62,breakfast_brunch,Breakfast & Brunch,VFIVZUyvMh59uxppfYV0IA,El Toro Loco Steakhouse Westchester,272,3.9,$$
63,latin,Latin American,kG8t6gBsarlvsxIocFUkAQ,Miranda Cuisine & Bar,119,4.4,$$
64,bars,Bars,kG8t6gBsarlvsxIocFUkAQ,Miranda Cuisine & Bar,119,4.4,$$
65,newamerican,New American,kG8t6gBsarlvsxIocFUkAQ,Miranda Cuisine & Bar,119,4.4,$$
66,latin,Latin American,zeD0dnP6grNMgO43Q5SlGg,Charlatam - Miami,26,4.8,NaN
67,italian,Italian,DM9KQiNPP0kNl3THdfyVGA,Tullio,115,4.5,NaN
68,desserts,Desserts,DM9KQiNPP0kNl3THdfyVGA,Tullio,115,4.5,NaN
69,wine_bars,Wine Bars,DM9KQiNPP0kNl3THdfyVGA,Tullio,115,4.5,NaN
70,salad,Salad,-FhPFfOrHIc9t69Qgrxmsw,Naked Farmer,95,4.7,NaN
71,newamerican,New American,-FhPFfOrHIc9t69Qgrxmsw,Naked Farmer,95,4.7,NaN
72,vegan,Vegan,-FhPFfOrHIc9t69Qgrxmsw,Naked Farmer,95,4.7,NaN
73,chinese,Chinese,byXml8ucI-z68JnV7aFpTg,China Express,193,4.1,$
74,asianfusion,Asian Fusion,eo2W_Hakq3SVGUsUSBHvGw,1-800-Lucky,1694,4.1,$$
75,bars,Bars,eo2W_Hakq3SVGUsUSBHvGw,1-800-Lucky,1694,4.1,$$
76,karaoke,Karaoke,eo2W_Hakq3SVGUsUSBHvGw,1-800-Lucky,1694,4.1,$$
77,wine_bars,Wine Bars,6F_9_I63Gr10_6JUyZs6nQ,Narbona Coconut Grove,279,4.1,$$
78,breakfast_brunch,Breakfast & Brunch,6F_9_I63Gr10_6JUyZs6nQ,Narbona Coconut Grove,279,4.1,$$
79,poke,Poke,6F_9_I63Gr10_6JUyZs6nQ,Narbona Coconut Grove,279,4.1,$$
80,tradamerican,American,g3U7lz6gUvmQ1nE4yQnvDA,The Thousand Sunny,129,4.4,$$
81,tradamerican,American,g3U7lz6gUvmQ1nE4yQnvDA,The Thousand Sunny,129,4.4,$$
82,spanish,Spanish,qR35bCaZAKozz0_ntddWgg,El Carajo International Tapas & Wines,815,4.1,$$
83,tapas,Tapas Bars,qR35bCaZAKozz0_ntddWgg,El Carajo International Tapas & Wines,815,4.1,$$
84,wine_bars,Wine Bars,qR35bCaZAKozz0_ntddWgg,El Carajo International Tapas & Wines,815,4.1,$$
85,italian,Italian,TamuPF7kUqJxIbn1_6yhTQ,Walrus Rodeo,187,4.4,$$$
86,burgers,Burgers,BrnGHnLCpbzFdpD0Ur-zLw,Juanchi's Burgers,563,4.0,$$
87,newamerican,New American,KXv8dsRBmOmGwRTqX_Rr8A,Ariete,750,4.1,$$$$
88,bars,Bars,KXv8dsRBmOmGwRTqX_Rr8A,Ariete,750,4.1,$$$$
89,sportsbars,Sports Bars,z1UW-zeI50bMEtGKFtrjmA,Grails Miami - Restaurant & Sports Bar,808,4.4,$$
90,newamerican,New American,z1UW-zeI50bMEtGKFtrjmA,Grails Miami - Restaurant & Sports Bar,808,4.4,$$
91,lounges,Lounges,z1UW-zeI50bMEtGKFtrjmA,Grails Miami - Restaurant & Sports Bar,808,4.4,$$
92,cuban,Cuban,Va5dWj_fl1AScswK7JmQ_A,Calle Dragones,131,4.1,$$$
93,cocktailbars,Cocktail Bars,Va5dWj_fl1AScswK7JmQ_A,Calle Dragones,131,4.1,$$$
94,asianfusion,Asian Fusion,Va5dWj_fl1AScswK7JmQ_A,Calle Dragones,131,4.1,$$$
95,taiwanese,Taiwanese,wsJQm_iSAj2jLeK9jaCQdg,Hi Pot Miami,287,4.4,$$
96,hotpot,Hot Pot,wsJQm_iSAj2jLeK9jaCQdg,Hi Pot Miami,287,4.4,$$
97,ramen,Ramen,wsJQm_iSAj2jLeK9jaCQdg,Hi Pot Miami,287,4.4,$$
98,italian,Italian,4J6suyRqgdRZXbLHdSuXRQ,Pastamia,159,4.6,$$
99,wine_bars,Wine Bars,4J6suyRqgdRZXbLHdSuXRQ,Pastamia,159,4.6,$$
100,pastashops,Pasta Shops,4J6suyRqgdRZXbLHdSuXRQ,Pastamia,159,4.6,$$
101,cuban,Cuban,CIXfW3GhufVHP9JBqSfykQ,Tin Tin,26,4.5,NaN
102,wine_bars,Wine Bars,CIXfW3GhufVHP9JBqSfykQ,Tin Tin,26,4.5,NaN
103,cocktailbars,Cocktail Bars,CIXfW3GhufVHP9JBqSfykQ,Tin Tin,26,4.5,NaN
104,bbq,Barbeque,gWeoN0eDy-tt05a9503jZg,Hometown Bar-B-Que,720,4.0,$$$
105,beerbar,Beer Bar,gWeoN0eDy-tt05a9503jZg,Hometown Bar-B-Que,720,4.0,$$$
106,cocktailbars,Cocktail Bars,gWeoN0eDy-tt05a9503jZg,Hometown Bar-B-Que,720,4.0,$$$

In [1]:
#Continuamos limpiando los datos en el avance_EDA.ipynb

In [51]:
df_yelp_vf.to_csv(
    r"C:\Users\magri\Downloads\yelp_miami.csv",
    index=False
)

In [52]:
df_yelp_vf = pd.concat(lista_consolidar, ignore_index=True)

df_yelp_vf.to_csv(
    r"C:\Users\magri\Downloads\yelp_miami_completo.csv",
    index=False
)